apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-generator
  namespace: {{ .Values.faultyDeployment.namespace }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-generator
  template:
    metadata:
      labels:
        app: task-generator
    spec:
      containers:
        - name: task-generator
          image: 637423247681.dkr.ecr.us-east-1.amazonaws.com/task-generator:{{ .Values.tag }} # replace with your actual image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"