apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: {{ .Values.slowSql.namespace }}  
  labels:
    app: message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
      annotations:
        groundcover/force-sample: "true"
    spec:
      containers:
      - name: message-service
        image: 637423247681.dkr.ecr.us-east-1.amazonaws.com/message-service:{{ .Values.tag }}
        imagePullPolicy: Always  # Ensures the image is always pulled
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "demo.cc1802as6snm.us-east-1.rds.amazonaws.com" # Replace with the actual RDS endpoint
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_NAME
          value: "demo"
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: {{ .Values.slowSql.namespace }}  
  labels:
    app: message-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: message-service
