apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
  namespace: {{ .Values.noisyNeighbor.namespace }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-service
  template:
    metadata:
      labels:
        app: news-service
    spec:
      containers:
        - name: news-service
          image:  637423247681.dkr.ecr.us-east-1.amazonaws.com/news-service:{{ .Values.tag }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
            limits:
              cpu: "1500m"
          volumeMounts:
            - mountPath: /tmp/backup-flag
              name: backup-flag
      nodeSelector:
        mission-critical: "true"  # Ensure this matches the taint on the nodes
      tolerations:
        - key: "mission-critical"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
      - name: backup-flag
        hostPath:
          path: /tmp/backup-flag # directory location on host
      
---
apiVersion: v1
kind: Service
metadata:
  name: news-service
  namespace: news  
spec:
  selector:
    app: news-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
