apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/base/opentelemetry-demo
  - ../../apps/base/groundcover-sensor
patches:
  - path: opentelemetry-demo.yaml
  - path: groundcover-sensor.yaml
