apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: karpenter
  namespace: flux-system
spec:
  type: "oci"
  interval: 1h
  provider: "aws"
  url: oci://public.ecr.aws/karpenter