apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  namespace: {{ .Values.faultyDeployment.namespace }} 
  labels:
    app: integration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      containers:
      - name: integration-service
        image: 637423247681.dkr.ecr.us-east-1.amazonaws.com/integration-service:v1
        imagePullPolicy: Always  # Ensures the image is always pulled
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: integration-service
  namespace: {{ .Values.faultyDeployment.namespace }} 
spec:
  selector:
    app: integration-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080