apiVersion: v1
kind: Namespace
metadata:
  name: task-generator
---
apiVersion: v1
kind: Namespace
metadata:
  name: scanner
---
apiVersion: v1
kind: Namespace
metadata:
  name: flower-shop 
---
apiVersion: v1
kind: Namespace
metadata:
  name: news
---
apiVersion: v1
kind: Namespace
metadata:
  name: chat